application.client.seismic-portal.domain=www.seismicportal.eu

quarkus.rest-client.seismic-portal-api.url=https://${application.client.seismic-portal.domain}
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.websockets-next.client.auto-ping-interval=PT30S